language: go

go:
  - 1.2
  - 1.3

install:
  - go get -v -t ./...
  - nvm use 0.10 && node --version && npm install -g dynalite
  - sudo pip install virtualenv && (cd test && make supervisord && ./venv/bin/supervisorctl start dynalite)

after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi

script:
  - go test -cover -v -integration -provider=dynalite ./...
